### ISSUE TITLE
Unable to resize 4K images

### ISSUE THREAD

**Issue by faizaankhan** [minimagick/minimagick#458] opened 2018-08-13 11:58 UTC
MiniMagick::Error (`mogrify -crop 20x30 +10+5 /tmp/mini_magick20180813-18341-gbxv6c.jpg` failed with error:
mogrify-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
mogrify-im6.q16: cache resources exhausted `/tmp/mini_magick20180813-18341-gbxv6c.jpg' @ error/cache.c/OpenPixelCache/3984.
):

**Comment by janko-m** [comment] 2018-08-13 12:04
This is an error caused by executing the ImageMagick command. I'm suspecting that there are some resource limits set, and they your 4K image is hitting those limits. See the ImageMagick documentation on increasing resource limits.

I will close this, as this is not a problem with MiniMagick, and I don't see how could this problem be solved in MiniMagick.

**Closed by janko-m** 2018-08-13 12:04 UTC
