### ISSUE TITLE
MiniMagick get_pixels gives "unable to write file"

### ISSUE THREAD

**Issue by jeffcovey** [minimagick/minimagick#552] opened 2022-11-20 13:00 UTC
This has been working for us for years as a quick-and-dirty way to check for duplicate images being uploaded to our Ruby on Rails site:

```
file.blob.open do |temp_file|
  file_data = MiniMagick::Image.open(temp_file.path)
  file_data.resize '1024x768'
  @md5 = Digest::MD5.hexdigest(file_data.get_pixels.join)
  # etc.
end
```

After recent Rails upgrades (I believe it started around 6.0.4; we're gradually moving to 7.0), this started throwing errors like:

```
/home/jeff/.rvm/gems/ruby-3.1.2/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:17:in `run': `convert /tmp/mini_magick20221120-1647726-dit0yb.png -depth 8 RGB:-` failed with error: (MiniMagick::Error) convert-im6.q16: unable to write file `-' @ error/constitute.c/WriteImage/1341.
```

I tracked the problem down to `get_pixels`. Everything works fine until there, including resizing the image in the previous line. Why do we get this error when calling `get_pixels`? Why is it trying to write a file when getting the pixels matrix?

Thanks for your help!
Jeff

**Comment by jeffcovey** [comment] 2022-11-23 18:30
I [asked this on StackOverflow](https://stackoverflow.com/questions/74537790/ruby-on-rails-minimagick-get-pixels-gives-unable-to-write-file), too, and someone confirmed the problem:

> There is probably something wrong with get_pixels. I just installed MiniMagick, opened an image and applied get_pixels and my console was left hanging ... (Rails 7, Ruby 3.1.0)

Can anyone help?

**Comment by jeffcovey** [comment] 2022-12-04 13:07
Is no one there?

**Comment by janko** [comment] 2024-06-07 15:07
Does your ImageMagick version support writing convert output to stdout (`-`)? Because the error message indicates that `-` is not recognized. MiniMagick uses that to get the pixels from ImageMagick without writing to temporary files.

Since tests for `MiniMagick::Image#get_pixels` are green on both IM6 and IM7, could you post a self-contained script that reproduces the issue only using MiniMagick (no Active Storage)? And also I will need the ImageMagick version.

I'll close this issue for now, because it seems the problem is old ImageMagick version.

**Closed by janko** 2024-06-07 15:07 UTC
