### ISSUE TITLE
`get_pixels` is not working properly

### ISSUE THREAD

**Issue by shivabhusal** [minimagick/minimagick#412] opened 2017-05-03 17:32 UTC
I am trying to get all the pixels to generate CSV file for train-data to `tensor-flow` machine learning algorithm. I intend to serialize all the pixels of every image in every row.

```ruby
require 'mini_magick'
require 'csv'
require 'pry'
image_data = MiniMagick::Image.open(File.expand_path('../../Train/digit_0/4558', __FILE__))

# now grayscaling the image_data
image_data.colorspace 'Gray'
pixels = image_data.get_pixels # returns pixels [R, G, B] format
# > [[232, 232, 232], [121, 121, 121], ...]

[1] pry(main)> image_data.get_pixels.map(&:count)
=> [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 16]
[2] pry(main)> image_data.get_pixels.map(&:count)
=> [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 16]
[3] pry(main)> image_data.get_pixels.map(&:count).count
=> 30

[5] pry(main)> image_data
=> #<MiniMagick::Image:0x00000001dcf978
 @info=
  #<MiniMagick::Image::Info:0x00000001dcf950
   @info={"raw:%m %w %h %b"=>"PNG 32 32 582B", "format"=>"PNG", "width"=>32, "height"=>32, "dimensions"=>[32, 32], "size"=>582, "human_size"=>"582B"},
   @path="/tmp/mini_magick20170503-32521-17lpgo">,
 @path="/tmp/mini_magick20170503-32521-17lpgo",
 @tempfile=#<File:/tmp/mini_magick20170503-32521-17lpgo (closed)>>
```
looks like `mini_magick` is not getting me all the pixel values. According to `imagemagick` the picture is `32x32` but the array I am getting is only `30x32` and also the last row seems to be incomplete.

Have I done any mistakes? can anybody tell how to fix?

Thanks and help will be appreciated

**Comment by shivabhusal** [comment] 2017-05-03 17:51
This is one of the images I am using
![4558](https://cloud.githubusercontent.com/assets/8004593/25674047/426bf7e2-3059-11e7-87f6-fc67e76e9dfa.png)

**Comment by janko-m** [comment] 2017-05-17 15:21
@giuseb Do you happen to have an idea about this one? \cc @LandonSchropp @Coolnesss

**Comment by LandonSchropp** [comment] 2017-05-19 04:05
If it helps, this is what I ended up doing instead:

```
def to_a
  @minimagick_image.format "png"
  chunky_image = ChunkyPNG::Image.from_io(StringIO.new(@minimagick_image.to_blob))

  # Convert the image to a 2D array of colors
  (0...chunky_image.width).map do |x|
    (0...chunky_image.height).map do |y|

      red = (chunky_image[x, y] & 0xff000000) >> 24
      green = (chunky_image[x, y] & 0x00ff0000) >> 16
      blue = (chunky_image[x, y] & 0x0000ff00) >> 8
      alpha = (chunky_image[x, y] & 0x000000ff)

      Color.new(red: red, green: green, blue: blue, alpha: alpha)
    end
  end
end
```

As you can see, I had to pull in ChunkyPNG and convert the minimagick blob over to that library to access the pixel data.

**Comment by giuseb** [comment] 2017-05-24 08:30
Sorry for the delay in responding, I am going to take a look asap

**Comment by giuseb** [comment] 2017-05-24 09:54
The sample image provided by @shivabhusal has a couple of black rows at the bottom, which was a clue, given that the number of rows captured by `get_pixels` was 30 instead of 32.

I confirmed the bug by adding more black rows, which causes `get_pixels` to get fewer and fewer rows.

It looks like there is something wrong with this bit of code:

```ruby
def get_pixels
    output = MiniMagick::Tool::Convert.new do |convert|
      convert << path
      convert.depth(8)
      convert << "RGB:-"
    end
    [...]
```
Note that `output.length` matches the position of the LAST non-black pixel.

Also note that the following raw code seems to work instead:

```ruby
output = `convert filename.png RGB:-`
pixels_array = output.unpack("C*")
```

**Comment by giuseb** [comment] 2017-05-24 13:45
@janko-m, here's another clue. If you replace the above block with this line...

          output, stderr = Open3.capture2("convert #{path} RGB:-")

...the image appears to be read properly.

**Comment by janko-m** [comment] 2017-05-24 13:48
@giuseb Thank you for the detective investigation! 🕵️

Could the `-depth 8` option be causing this?

**Comment by giuseb** [comment] 2017-05-26 15:37
@janko-m, I believe that `-depth 8` is a default. In any case, the following works as well:

    output, stderr = Open3.capture2("convert #{path} -depth 8 RGB:-")

I tried to find out where the trimming occurs, but the function call stack is quite deep, I got lost... 😳

**Comment by drdent** [comment] 2017-06-29 11:15
i have a similar bug with this image:
![grafik](https://user-images.githubusercontent.com/646573/27685083-f4296b3c-5ccc-11e7-9327-5b2c0d37dd0e.png)


The last blue value is missing:

`pry> img.get_pixels.last
=> [[151, 192, 122],
 [133, 165, 111],
 [120, 149, 112],
 [116, 143, 133],
 [128, 151, 134],
 [135, 165, 147],
 [162, 201, 157],
 [172, 211]]

pry> img.get_pixels.last.map(&:count)
=> [3, 3, 3, 3, 3, 3, 3, 2]
`

**Comment by LAndreas** [comment] 2017-07-04 15:46
I've done some debugging with the image provided by @drdent 

The problem here is this line: https://github.com/minimagick/minimagick/blob/b36339f1ffb2b42ae815d222bffc3b5d797e2281/lib/mini_magick/tool.rb#L95
The generated output is stripped by `MiniMagick::Tool#call` before returned.

@drdent not the **last blue value** is missing, the **first red value** is missing in your picture.

Following code was used for debugging:
```ruby
file = "<path to provided image>"
`convert #{file} -filter Gaussian -resize 8x8! test2.png` # convert test image with Gaussian filter

output, *_ = Open3.capture3('convert test.png -depth 8 RGB:-', binmode: true)

output.unpack('C*').each_slice(3).each_slice(8).first
# => [[13, 16, 18], [17, 19, 27], [40, 42, 73], [47, 47, 82], [43, 41, 69], [28, 27, 46], [20, 20, 35], [22, 21, 39]

output.strip.unpack('C*').each_slice(3).each_slice(8).first
# => [[16, 18, 17], [19, 27, 40], [42, 73, 47], [47, 82, 43], [41, 69, 28], [27, 46, 20], [20, 35, 22], [21, 39, 17]]
# Note: Output is shifted by 1 element to the left
```
In this example the first character in `output` is `\r` if interpreted in an non-binary way (as done by `strip`).

A possible fix/workaround would be something like this:
```ruby
def get_pixels
  output = ""
  convert = MiniMagick::Tool::Convert.new
  convert << path
  convert.depth(8)
  convert << "RGB:-"
  convert.call do |stdout, _, _|
    output = stdout
  end

  pixels_array = output.unpack("C*")
  pixels = pixels_array.each_slice(3).each_slice(width).to_a

  # deallocate large intermediary objects
  output.clear
  pixels_array.clear

  pixels
end
```

Or maybe a more elegant way would be to introduce a `binary` mode in `MiniMagick::Tool`?

**Comment by janko-m** [comment] 2017-07-04 16:38
This "strip" is actually totally unnecesaary, what I actually wanted here is just to remove a single trailing newline that's there in non-binary outputs, which could be done with chomp("\n").

**Comment by janko-m** [comment] 2017-07-04 23:43
I just pushed a fix which only removes the trailing newline from the output, instead of stripping all trailing whitespace. Let me know if this resolves the issue, and I'll release a new MiniMagick version with this fix.

**Comment by LAndreas** [comment] 2017-07-05 07:15
@janko-m thanks for the fast responds!

`chomp("\n")` fixes this problem for all leading separation characters (`\n` & `\r`), but if there is a trailing `\n` it will be stripped...

I've created an example which demonstrates this:
![test3](https://user-images.githubusercontent.com/1185693/27853125-e40fb9f6-6161-11e7-980e-3e8b2ef786b3.png)
(Sorry, but is it only 8x8 pixels)

```ruby
output, *_ = Open3.capture3('convert test3.png -depth 8 RGB:-', binmode: true)
output.chomp("\n").unpack('C*').each_slice(3).each_slice(8).to_a.last
# => => [[133, 149, 189], ..., [149, 163, 201], [158, 171]]
```

@janko-m do you know if it is really necessary to strip trailing whitespaces? Or can we safely remove this `chomp("\n")` without breaking other parts of the gem?

**Comment by janko-m** [comment] 2017-07-05 08:51
@LAndreas Thanks for the report. I tried removing the `chomp("\n")` and running the test suite, and there is only one test that broke:

```
Failures:                                                                                                                                                                            
                                                                                                                                                                                     
  1) With GraphicsMagick MiniMagick::Image#[] reads exif                                                                                                                             
     Failure/Error: expect(subject["EXIF:Flash"]).to eq "0"                                                                                                                          
                                                                                                                                                                                     
       expected: "0"                                                                                                                                                                 
            got: "0\n"                                                                                                                                                               
                                                                                                                                                                                     
       (compared using ==)                                                                                                                                                           
                                                                                                                                                                                     
       Diff:                                                                                                                                                                         
                                                                                                                                                                                     
     # ./spec/lib/mini_magick/image_spec.rb:352:in `block (5 levels) in <top (required)>'
```

I would rather not remove it because people are likely relying on it. But I think your workaround with passing a block to `MiniMagick::Tool#call` is great, would you mind sending a PR for that (with specs using the image you've created)?

**Comment by LAndreas** [comment] 2017-07-05 11:27
@janko-m i've submitted a merge request (#421) (with a slightly different solution).

**Closed** 2017-07-06 09:48 UTC

**Comment by janko-m** [comment] 2017-07-06 09:57
Thanks to collaborative debugging and @LAndreas figuring out the bug, this issue should now be fixed in latest version of MiniMagick (4.8.0).

**Comment by davidwilliam** [comment] 2017-07-09 23:16
Out of curiosity: What's the command line equivalent for the get_pixels method? Looking into the implementation, I see that the path, the depth, and the RGB flag are defined. However, what's the complete command that is being executed in order to retrieve the blob that will be treated in order to get the RGB pixel array? Thank you.

**Comment by janko-m** [comment] 2017-07-10 01:31
You can see the complete command by turning on logging:

```rb
MiniMagick.logger.level = Logger::DEBUG
```

**Comment by davidwilliam** [comment] 2017-07-10 01:36
Thank you @janko-m . That did it.
