### ISSUE TITLE
Identify fails, works fine in development

### ISSUE THREAD

**Issue by brian-nicholls** [minimagick/minimagick#551] opened 2022-11-17 21:13 UTC
Here is my code, which works perfectly in development:
```ruby
    watermark_path = "#{Rails.root}/app/assets/images/watermark.png"
    source_pdf     = MiniMagick::Image.new(path_file) # "/tmp/dp_1526_1668719397004.pdf"
    watermark_img  = MiniMagick::Image.open(watermark_path)
    composite_img = source_pdf.composite(watermark_img) do |c| # code breaks here
      c.compose 'overlay'
      c.tile
    end
```
But when it goes to staging, which is Dockerized, it breaks with the following error:
```
MiniMagick::Error (`identify -format %m %w %h %b /tmp/dp_1513_1668718915070.pdf[0]` failed with error:
):
```
I've tried so many things, any help is greatly appreciated!

**Comment by janko** [comment] 2022-11-18 05:35
Do you get the same error on the command-line within Docker?

**Comment by brian-nicholls** [comment] 2022-11-18 13:29
I get no output whatsoever when running identify in the command line. I also tried running identify via Ruby using backticks, and it just returns an empty string. I am now using a slightly different approach, and I get the same result when trying to get the document's width (again, works fine in dev)
```ruby
source_pdf = MiniMagick::Image.open(path_file)
doc_dimensions  = [source_pdf.width, source_pdf.height] # fails here with below error
```
![image](https://user-images.githubusercontent.com/72148575/202716122-9b2bda24-983c-460d-ab28-2688db129aca.png)

**Comment by janko** [comment] 2022-11-18 13:43
And the exit status code? You can already see from the Ruby exception that there is no error output, but the exit status of the shell command was likely nonzero.

**Comment by brian-nicholls** [comment] 2022-11-18 14:01
The shell command just goes to a new line, no output, unless I am missing something?

**Comment by janko** [comment] 2022-11-18 16:37
Every shell command has a status code. You can run `echo $?` to see the status of the last command. If it's nonzero, the command errored (even if there is no output).

**Comment by janko** [comment] 2022-12-07 09:12
I'm closing this, as the issue is most likely that the `identity` command returned a nonzero exit status, which indicates an error. You might be using a different version of ImageMagick in locally, so that's why you might not be experiencing this locally.

**Closed by janko** 2022-12-07 09:12 UTC
