### ISSUE TITLE
Deadlock with Open3.capture3

### ISSUE THREAD

**Issue by jcoyne** [minimagick/minimagick#347] opened 2016-01-07 17:19 UTC
```
No live threads left. Deadlock?

/usr/local/lib/ruby/2.2.0/open3.rb:265:in `value'
/usr/local/lib/ruby/2.2.0/open3.rb:265:in `block in capture3'
/usr/local/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
/usr/local/lib/ruby/2.2.0/open3.rb:93:in `popen3'
/usr/local/lib/ruby/2.2.0/open3.rb:252:in `capture3'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:43:in `execute_open3'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:32:in `block (2 levels) in execute'
/usr/local/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:31:in `block in execute'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/logger.rb:32:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/logger.rb:32:in `block in benchmark'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/logger.rb:32:in `benchmark'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/logger.rb:21:in `debug'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:30:in `execute'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:14:in `run'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:79:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:40:in `new'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/image.rb:494:in `mogrify'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/image.rb:388:in `method_missing'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:32:in `block in create_resized_image'
```

**Comment by bensie** [comment] 2016-01-16 15:17
@jcoyne Please provide more info - code sample and image where this happens. We need to know how to reproduce.

**Comment by janko-m** [comment] 2016-02-04 05:05
I'm aware that it's difficult to reproduce a deadlock, but I'm pretty sure that this bug doesn't come from MiniMagick, maybe there is a bug in the `open3` standard library, or the `timeout` standard library if you have `MiniMagick.timeout` set (in that case it could be the combination, since `Open3.capture3` is called inside of the `Timeout.timeout` block).

MiniMagick doesn't use anything thread-related directly, so I will close this unless it's proven that it comes from MiniMagick.

**Comment by jeremy** [comment] 2016-05-15 19:53
Common problem with open3 due to fixed-size pipes and blocking reads: https://bugs.ruby-lang.org/issues/9082

Some older discussion: http://coldattic.info/shvedsky/pro/blogs/a-foo-walks-into-a-bar/posts/63

And in official docs: http://ruby-doc.org/stdlib-2.3.0/libdoc/open3/rdoc/Open3.html#method-c-popen3

Would think that `Open3.capture3` would eliminate this, though, by using nonblocking IO internally!

**Comment by janko-m** [comment] 2016-05-16 17:42
@jeremy Thank you very much for the detailed references. MiniMagick already uses `Open3.capture3`, you probably meant `Open3.popen3` (which `capture3` uses underneath). I will have to figure out what is the right way to do this; I'm kind of disappointed that `Open3.capture3` isn't already deadlock-free, but that I need to implement my own safer version of it.

**Comment by jeremy** [comment] 2016-05-16 18:09
I did mean `capture3`: I saw you're using it now and was surprised that it isn't _already_ insulating you from deadlocks. I hit the same in my app and was similarly surprised 😊

**Comment by janko-m** [comment] 2016-12-03 07:12
I honestly don't know how to work around this error, since MiniMagick needs Open3 for separating stdout from stderr. I think `Open3.capture3` just has to be fixed in Ruby itself.

**Closed by janko-m** 2016-12-03 07:12 UTC

**Comment by janko-m** [comment] 2016-12-03 07:15
Actually, a workaround is to switch MiniMagick to use the `posix-spawn` gem for executing shell commands:

```rb
MiniMagick.shell_api = "posix-spawn"
```
