### ISSUE TITLE
Getting MiniMagick::Invalid due to improper image header

### ISSUE THREAD

**Issue by ciaoben** [minimagick/minimagick#400] opened 2017-01-25 11:26 UTC
On my dev server everything was going well with ´4.5.1´, but when deployed to a staging server I get

```
MiniMagick::Invalid
`identify /tmp/mini_magick20170125-5689-6stpeb.png` failed with error: identify: improper image header `/tmp/mini_magick20170125-5689-6stpeb.png' @ error/png.c/ReadPNGImage/3921.
```

The versions of imagemagick are the same.

So I decided to try to update the gem to `4.6.0` on dev server, and now I get the same error.

Any clue?

**Comment by janko-m** [comment] 2017-01-25 12:02
This error is most likely due to differences in ImageMagick versions on your dev and staging server, because the `identify` command that you ran fails. The `identify` command is run whenever a `MiniMagick::Image` is instantiated, and an error is raised if the command fails.

If you want to turn off validations, see https://github.com/minimagick/minimagick#image-validation. But the validations will only raise when ImageMagick detects an invalid image, which it might not be able to process.

**Comment by ciaoben** [comment] 2017-01-25 12:14
sorry, but I wrote in the original post that on my dev machine, with version 4.5.1 of the gem it worked,and after the update stopped working. 

I have only updated the gem ,not image magick, and anyway the version of imagemagick it is the same on both server.

**Comment by ciaoben** [comment] 2017-01-25 12:16
Here is the version of imagemagick on both dev and staging:

# convert -version
Version: ImageMagick 6.9.7-5

**Comment by janko-m** [comment] 2017-01-25 12:29
Can attach the PNG that fails on 4.6.0, but doesn't on 4.5.1?

**Comment by ciaoben** [comment] 2017-01-25 12:55
Sure, but honestly it seems to happen with all images.. 

http://imgur.com/a/Bi7Sx
http://imgur.com/a/AGuiS

**Comment by ciaoben** [comment] 2017-01-31 10:03
Nothing new?

**Comment by janko-m** [comment] 2017-01-31 10:20
I tried with the first file, and I cannot reproduce it. The following script:

```rb
require "mini_magick"

puts MiniMagick.version
puts MiniMagick.cli_version

MiniMagick.logger.level = Logger::DEBUG

image = MiniMagick::Image.open("http://i.imgur.com/dWPZCKj.png")
puts image.valid?
```

produces this output locally:

```
4.6.0
6.9.5-1
D, [2017-01-31T21:16:00.318906 #23922] DEBUG -- : [0.01s] identify /var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/mini_magick20170131-23922-psk3h6.png
D, [2017-01-31T21:16:00.329263 #23922] DEBUG -- : [0.01s] identify /var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/mini_magick20170131-23922-psk3h6.png
true
```

Unless you can come up with a self-contained script that reproduces the bug, I'm afraid I can't be of much help. I only know that in Shrine someone reported ImageMagick throwing a `improper image header` error when the file was empty.

Basically, you need to find out why ImageMagick itself throws that error on production, but not on development. MiniMagick only propagates the error that ImageMagick returned.

**Comment by janko-m** [comment] 2017-02-12 08:40
@ciaoben I tried the above script for the current newest ImageMagick version (`7.0.4-7`), and the image is again successfully validated. I will close this until someone manages to come up with a self-contained example that reproduces the bug.

**Closed by janko-m** 2017-02-12 08:40 UTC

**Comment by cupojoe** [comment] 2017-05-03 15:01
@janko-m where you able to figure this out? I have a very similar problem where some of my bitrise.io builds fail because of this error and some succeed, literally without changing a thing in our code base. The only thing I can think of that might be different is the machine that is available at the time of the build might have some different version, but with limited access to those, it's hard to reproduce consistently.

**Comment by janko-m** [comment] 2017-05-03 15:24
@cupojoe The thing is, MiniMagick only does what ImageMagick told it to do here. MiniMagick asked ImageMagick whether the image is valid, by calling `identify`, and ImageMagick responded with a non-zero exit status and an error message `improper image header `/tmp/mini_magick20170125-5689-6stpeb.png' @ error/png.c/ReadPNGImage/3921`, in other words that the image is invalid, and then MiniMagick raises an error. I don't know what would you like MiniMagick to do here.

The problem was that ImageMagick identified the image as invalid, MiniMagick just communicated this as an error. If you believe that ImageMagick returned this error message for no good reason (that it can in fact process those images), you can tell MiniMagick not to perform these validations.

**Comment by cupojoe** [comment] 2017-05-03 22:13
I think disabling the validation is never a good idea. What threw me off here is that this wasn't happening on every build (still don't know why). But when I replaced the images, it was fixed.

**Comment by graciano** [comment] 2018-03-01 21:52
In the case someone got here getting the `MiniMagick::Invalid` error, here's something I came up and solved the problem in my case:

I had an old minimagik gem installed and updated it, but it was not enough. Still getting the same error. Only when I updated my `imagemagik` OS software from `7.0.5-4`  to `7.0.7-24`.
