### ISSUE TITLE
A JSON::ParserError occurred

### ISSUE THREAD

**Issue by PeterMozesMerl** [minimagick/minimagick#423] opened 2017-07-18 16:49 UTC
I started receiving emails of JSON::ParserError exceptions once in a while when the user uploads an image. 

I don’t have the specific images. I save every image caused an ImageMagick::ThisOrThat exception (and they were all user errors or corrupt images).

But the JSON::ParserError is not handled there. I will include it but it will take time and the exception doesn’t happen often.

Based on my emails, it has been occuring since 1st March, which was few days after I deployed a change that maximizes the quality of the uploaded image.

The backtrace attach is all I have (sent by ExceptionNotification). It’s strange if I call JSON.parse on the string you see in the backtrace, it gets parsed. At least the one I tried did.

I would attach the specific image if I could. I don’t deploy each day, and the exception happened only 33 times of a few ten million of page views. It might take a time to find and save a specific image for debugging.

I can see a strange character in the "comment" field on GitHub. But when I copy it to irb, it’s a space.

The number is almost always 743. It was 419 two times, 409 two times, 784 two times. That’s all.

```ruby
tmp_img.quality(maximum_value) if original_img.data['quality'].blank? || original_img.data['quality'] > maximum_value
 ```

```
A JSON::ParserError occurred in images#create:

  743: unexpected token at '{
  "image": {
    "name": "/tmp/mini_magick20170718-69587-1qd9hbh.jpeg[0]",
    "format": "JPEG",
    "formatDescription": "Joint Photographic Experts Group JFIF format",
    "mimeType": "image/jpeg",
    "class": "DirectClass",
    "geometry": {
      "width": 1280,
      "height": 960,
      "x": 0,
      "y": 0
    },
    "resolution": {
      "x": "72",
      "y": "72"
    },
    "printSize": {
      "x": "17.777777777777778567",
      "y": "13.333333333333333925"
    },
    "units": "PixelsPerInch",
    "type": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 8,
    "baseDepth": 8,
    "channelDepth": {
      "red": 8,
      "green": 8,
      "blue": 8
    },
    "pixels": 1228800,
    "imageStatistics": {
      "all": {
        "min": "46",
        "max": "255",
        "mean": "180.931",
        "standardDeviation": "52.6511",
        "kurtosis": "-1.0767",
        "skewness": "-0.00895097"
      }
    },
    "channelStatistics": {
      "red": {
        "min": "46",
        "max": "255",
        "mean": "181.173",
        "standardDeviation": "55.9718",
        "kurtosis": "-1.03302",
        "skewness": "-0.230587"
      },
      "green": {
        "min": "58",
        "max": "255",
        "mean": "175.331",
        "standardDeviation": "52.5951",
        "kurtosis": "-1.1273",
        "skewness": "0.216887"
      },
      "blue": {
        "min": "56",
        "max": "255",
        "mean": "186.289",
        "standardDeviation": "48.5512",
        "kurtosis": "-1.14997",
        "skewness": "0.0986408"
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "backgroundColor": "#FFFFFF",
    "borderColor": "#DFDFDF",
    "matteColor": "#BDBDBD",
    "transparentColor": "#000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 1280,
      "height": 960,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "iterations": 0,
    "compression": "JPEG",
    "quality": 95,
    "orientation": "TopLeft",
    "properties": {
      "comment": "",
      "date:create": "2017-07-18T15:08:37+02:00",
      "date:modify": "2017-07-18T15:08:37+02:00",
      "exif:ColorSpace": "1",
      "exif:ComponentsConfiguration": "1, 2, 3, 0",
      "exif:DateTime": "2014:04:21 17:42:32",
      "exif:DateTimeDigitized": "2014:04:21 17:42:32",
      "exif:DateTimeOriginal": "2014:04:21 17:42:32",
      "exif:ExifImageLength": "960",
      "exif:ExifImageWidth": "1280",
      "exif:ExifOffset": "236",
      "exif:ExifVersion": "48, 50, 50, 48",
      "exif:ExposureMode": "0",
      "exif:ExposureProgram": "3",
      "exif:ExposureTime": "1/14",
      "exif:Flash": "0",
      "exif:FlashPixVersion": "48, 49, 48, 48",
      "exif:FNumber": "26/10",
      "exif:FocalLength": "355/100",
      "exif:GPSInfo": "596",
      "exif:GPSVersionID": "2, 2, 0, 0",
      "exif:ImageLength": "960",
      "exif:ImageWidth": "1280",
      "exif:InteroperabilityOffset": "566",
      "exif:ISOSpeedRatings": "200",
      "exif:Make": "SAMSUNG",
      "exif:MaxApertureValue": "300/100",
      "exif:MeteringMode": "3",
      "exif:Model": "GT-S5830i",
      "exif:Orientation": "1",
      "exif:ResolutionUnit": "2",
      "exif:SceneCaptureType": "0",
      "exif:SceneType": "1",
      "exif:Software": "S5830iXXLD3",
      "exif:thumbnail:Compression": "6",
      "exif:thumbnail:InteroperabilityIndex": "R98",
      "exif:thumbnail:InteroperabilityVersion": "48, 49, 48, 48",
      "exif:thumbnail:JPEGInterchangeFormat": "668",
      "exif:thumbnail:JPEGInterchangeFormatLength": "17705",
      "exif:thumbnail:ResolutionUnit": "2",
      "exif:WhiteBalance": "0",
      "exif:XResolution": "72/1",
      "exif:YCbCrPositioning": "1",
      "exif:YResolution": "72/1",
      "jpeg:colorspace": "2",
      "jpeg:sampling-factor": "2x1,1x1,1x1",
      "signature": "9d6f15dee6a144e3667bdb5e4ba4b32fcfa90868042819a982df687c9b8f549f"
    },
    "profiles": {
      "exif": {
        "length": "18379"
      }
    },
    "artifacts": {
      "filename": "/tmp/mini_magick20170718-69587-1qd9hbh.jpeg[0]"
    },
    "tainted": false,
    "filesize": "332360B",
    "numberPixels": "1228800",
    "pixelsPerSecond": "52428800B",
    "userTime": "0.023u",
    "elapsedTime": "0:01.023",
    "version": "ImageMagick 6.9.8-9 Q16 amd64 2017-07-13 http://www.imagemagick.org"
  }
}'
  app/models/image.rb:302:in `maximize_quality'
```

**Comment by PeterMozesMerl** [comment] 2017-07-18 16:52
I doubt this would help much:

 ```
A JSON::ParserError occurred in images#create:

  409: unexpected token at '" V"],        "Byline[2,80]": ["                                "],        "Copyright String[2,116]": ["                                                      "],        "length": "103"
      },
      "xmp": {
        "length": "5972"
      }
    },
    "artifacts": {
      "filename": "/tmp/mini_magick20170515-20286-1ybxnbi.jpeg[0]"
    },
    "tainted": false,
    "filesize": "2.292MB",
    "numberPixels": "12.21M",
    "pixelsPerSecond": "60.12MB",
    "userTime": "0.227u",
    "elapsedTime": "0:01.203",
    "version": "ImageMagick 6.9.6-4 Q16 amd64 2017-04-13 http://www.imagemagick.org"
  }
}'
  app/models/image.rb:302:in `maximize_quality'
```

**Comment by janko-m** [comment] 2017-07-20 21:58
Thank you for the detailed info! This is really strange, because MiniMagick also uses `JSON.parse` to parse the JSON, so I don't get why MiniMagick fails but the manual `JSON.parse` succeeds. Note that there was already a report of a `JSON::ParserError` in https://github.com/minimagick/minimagick/issues/410, but in that case not even manual `JSON.parse` failed.

One idea where the issue could be is string encoding. MiniMagick always returns output from ImageMagick commands in binary encoding (`ASCII-8BIT`), so it might be that the JSON parsing is failing for binary encoding, but when you copy the JSON string from the error message and paste it into a Ruby file for debugging, it will now be in UTF-8 encoding because that's Ruby's default encoding for strings. I tried to `.force_encoding(Encoding::BINARY)` the JSON you provided, but it still works. However, perhaps the original JSON string retrieved from the command has some different characters then when it's converted to UTF-8 and back.

We can test whether that's the case if you manage to obtain one image that errors, or you can rescue `JSON::ParserError` and `File.binwrite("tmp/data.json", MiniMagick::Tool::Convert.new { |c| c << path << "json:" })`, and afterwards you can manually read it and try to parse it, first with `JSON.parse(File.binread("tmp/data.json"))` and then with `JSON.parse(File.binread("tmp/data.json").force_encoding(Encoding::UTF_8))` or just `JSON.parse(File.read("tmp/data.json"))`.

If the bug does turn out to be caused by encoding, I think a good solution would be for MiniMagick to `force_encoding(Encoding::UTF_8)` the return JSON string. That command should never fail, because it doesn't modify the bytes (unlike `String#encode`), it rather just makes Ruby treat it with a different encoding.

**Comment by PeterMozesMerl** [comment] 2017-07-23 13:50
The mystery is how rarely it happens compared to the page views.

I already put there the exception to save the file. I’m going to deploy it soon. I’ll tell you when I have a test file.

**Comment by PeterMozesMerl** [comment] 2017-09-03 21:34
Yes, it happened two more times, and I can reproduce it as I saved the file.

The following line was executed in Rails console. The gem was already loaded. I simplified the case, and double-checked it with a normal image.

```ruby
content = File.read('normal.jpg'); puts content.encoding; content.force_encoding('BINARY'); puts content.encoding; image = MiniMagick::Image.read(content); puts image.width; puts image.data['quality']
UTF-8
ASCII-8BIT
300
60
```

Here is the same with the problematic image:

```ruby
content = File.read('json.jpg'); puts content.encoding; content.force_encoding('BINARY'); puts content.encoding; image = MiniMagick::Image.read(content); puts image.width; puts image.data['quality']
UTF-8
ASCII-8BIT
3264
JSON::ParserError: 765: unexpected token at '{
...
```

Please understand I attach a user-uploaded photo. I take no responsibility for its content in any way. But it’s not a disturbing one. I can open and see the photo in macOS Preview. identify works on it as well.

I’m not attaching the normal file as the code above works with the 99.9% of the images.

[json.zip](https://github.com/minimagick/minimagick/files/1273268/json.zip)

**Comment by janko-m** [comment] 2017-09-12 10:05
The problem is in `xmp:UserComment`:

<img width="591" alt="screen shot 2017-09-12 at 12 01 54" src="https://user-images.githubusercontent.com/795488/30320199-3cd9924c-97b2-11e7-879a-48669a35032f.png">

As you can see, there is this `^R` escape sequence. If I remove it, the JSON parses normally.

However, the *JavaScript* JSON parser throws an error with or without `^R`, so it still doesn't seem to be valid JSON (I think we can consider the JavaScript parser to be the reference implementation). MiniMagick cannot fix broken JSON; if I decide to remove all `^R` characters, another image will pop up which is missing a comma, or has another faulty character. So invalid JSON should be fixed in ImageMagick itself.

**Closed by janko-m** 2017-09-12 10:05 UTC

**Comment by PeterMozesMerl** [comment] 2017-09-12 11:15
I see your point. Should I submit this to upstream, or will you?

**Comment by janko-m** [comment] 2017-09-12 11:17
@PeterMozesMerl If you are able to open an issue there, that would be very helpful.

**Comment by PeterMozesMerl** [comment] 2017-09-12 11:20
I’ll do it. Thank you for the information.
