### ISSUE TITLE
Mini magick convert png as white with transparent

### ISSUE THREAD

**Issue by manojvrv** [minimagick/minimagick#382] opened 2016-11-15 05:48 UTC
I am using carrierwave(Mini Magick) to convert a image as white transparent for Android notification icon.

http://developer.android.com/design/patterns/notifications.html

```
image = MiniMagick::Image.new("input.png") do |cmd|
        cmd.transparent("#ffffff")
        cmd.channel "a"
        cmd.separate
        cmd.negate
end
```
But I am getting the image as 'black on white' instead of "white on black"

This how i want the transparent image to look like
https://i.stack.imgur.com/knZhA.png

**Comment by janko-m** [comment] 2016-12-03 04:18
Closing as an exact duplicate of #380 😉

**Closed by janko-m** 2016-12-03 04:18 UTC
