### ISSUE TITLE
GIF Upload Causes Memory Leak breaking entire site (App Crashed Error on Heroku) ERROR H10

### ISSUE THREAD

**Issue by callancarr** [minimagick/minimagick#378] opened 2016-09-08 09:46 UTC
I've posted this issue in Carrierwave and it seems the conclusion is the problem is related to MiniMagick so I have raised an issue here. This is a really serious issue i've run into and it seems to relate to gif uploads.

I have to process every image to make it square for my app. The standard resize doesn't work for GIFs, it distorts them, so I had to use a work around I found online. Below is my full uploader code

```
class PictureUploader < CarrierWave::Uploader::Base

  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  include CarrierWave::MiniMagick
  include ::CarrierWave::Backgrounder::Delay

  # Auto-orient
  process :auto_orient

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Prevent sideways on mobile
  def auto_orient
    manipulate! do |img|
      img = img.auto_orient
    end
  end

  def resize_with_animate(width,height)
    manipulate! do |img|
    if img[:format].downcase == 'gif'
      #coalesce animated gifs before resize.
      img.coalesce
    end
    img.resize "#{width}x#{height}>"
    img = yield(img) if block_given?
    img
    end
  end


  # Create different versions of your uploaded files:
  version :thumb do
    process :resize_with_animate => [640,640]
    process :resize_to_fill => [640, 640]
  end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
     %w(jpg jpeg gif png)
  end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  # def filename
  #   "something.jpg" if original_filename
  # end
end
```
`
So essentially fairly standard, I have tried using carrierwave_backgrounder to make sure that the app is processing things normally. What seems to happen is that during processing the GIF a memory leak occurs. I then hit a "Memory Limit Reached" exception and my whole app dies, so really serious since we serve about 5k people and simply uploading a GIF breaks the site.

The obvious solution is to prevent GIF uploads, but it's very important to my clients they are kept. What should I do and what is causing this? Is this an internal issue with carrierwave.

**Comment by janko-m** [comment] 2016-09-08 09:54
@callancarr Me again 😃. I meant that this is likely an issue with **Image**Magick, not MiniMagick. It would be great if you could make a script which processes many GIF files and proves that there is a memory leak, which you can then include into the bug report on the ImageMagick bug tracker. 

Ideally it's best to execute ImageMagick commands directly (as I said, you can get the ImageMagick commands that MiniMagick executes by turning on MiniMagick logging), so that the ImageMagick team doesn't have to know Ruby.

**Comment by callancarr** [comment] 2016-09-08 10:01
Ah crap sorry Janko, wrong place again! I figured I'm using Minimagick so it's best to ask here. Shall we close these two issues and put them to ImageMagick.

I really need to resolve this issue quickly, as far as I can see its related to the Gem and I cannot proceed until that's done. I find it hard to understand why processing a single GIF can break an entire site that serves 1000's at a time.

I'll compile some research with logging and pass it to the ImageMagick team. thanks!

**Comment by callancarr** [comment] 2016-09-08 10:02
I think this is the issue! @janko-m 

https://github.com/ImageMagick/ImageMagick/issues/263

**Comment by janko-m** [comment] 2016-09-08 10:22
@callancarr Great. Yeah, I think you can close the issues on CarrierWave and here.

I don't know what is a good workaround here. I'm looking forward to [ImageFlow](https://github.com/imazen/imageflow), I think it should have these issues taken care of (because it will have a much narrower scope than ImageMagick).

**Comment by callancarr** [comment] 2016-09-08 10:37
@janko-m  I'm clsoing the issue and going to raise the issue in CarrierWave-backgrounder because my inspection leads me to believe this is casuing the problems.

**Closed** 2016-09-08 10:36 UTC

**Comment by a-barbieri** [comment] 2017-10-27 06:48
@tubebot I'd love to know where you opened the new thread and if you were able to solve the issue. This problem has been bugging me for weeks and I haven't found a proper solution yet.

**Comment by harshal27** [comment] 2017-11-27 07:36
@tubebot @a-barbieri is the issue resolved ? Plz let me know the workaround .... the problem has been bugging me too

**Comment by a-barbieri** [comment] 2017-11-27 09:30
The issue is a known problem of MiniMagic therefore I'm planning to switch to RMagic. I'll let you know if that resolve the issue entirely.

**Comment by harshal27** [comment] 2017-11-27 10:52
@a-barbieri I think the issue is with image magick .... I tried using RMagic and its also not working properly

**Comment by a-barbieri** [comment] 2017-11-27 11:26
Then I don't have any solution. And don't know if someone from either MiniMagick or RMagick will sort it out any time soon.

**Comment by thiagofm** [comment] 2017-12-13 14:18
MiniMagick and Rmagick are just gems, they use both imagemagick, a computer program, one exposes its shell api, the other its C API. The problem resides on imagemagick, how it handles gifs and whatnot. It's a piece of software that has been lasting for decades but is full of bugs, as it's domain is definitely complex, jpgs, gifs etc are very complex and weird formats and I find it actually amusing that in end, it still works.

A solution would be to use something simpler, as @janko-m suggested that could substitute imagemagick(and also perhaps minimagick and rmagick), if it fits your use-case. Unfortunately, for many, the wide range of functionality that imagemagick provides is hard to get by.
